version: "3"
services:
  nuxt:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/nuxt
    # command: yarn run serve
    ports:
      - 80:8080
    stdin_open: true
    tty: true
    